# Wi-Fi (WPA2) on DHCP
# Use with: go-udap set <mac> --config wifi-wpa2.conf --reboot
# Edit the SSID and pre-shared key to match your network.
interface=0
lan_ip_mode=1
wireless_SSID=YourNetworkName
wireless_wpa_on=1
wireless_wpa_mode=2
wireless_wpa_cipher=2
wireless_wpa_psk=your-pre-shared-key

# Set your music server's IP:
server_address=192.168.1.250
