// docs is a build-time tool that generates man pages for go-udap from
// the cobra command tree. Run it via `task man` or directly:
//
//	go run ./cmd/docs              # writes ./man/*.1
//	go run ./cmd/docs ./some/dir   # writes ./some/dir/*.1
//
// The generated set is:
//
//	go-udap.1
//	go-udap-<subcommand>.1   (discover, info, read, get, set, reboot,
//	                          getip, interfaces, completion, help)
//
// Why a separate binary rather than a hidden subcommand of go-udap (the
// existing pattern for __dump-completions): cobra/doc pulls in a
// markdown→roff conversion stack (go-md2man, blackfriday). Keeping it
// out of the main module's import path keeps the production binary lean.
package main

import (
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"go-udap/cli"
)

func main() {
	outDir := "./man"
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}

	root := cli.Root()
	// Suppress the "Auto generated by spf13/cobra on <date>" footer.
	// Otherwise every regeneration produces a noisy diff and release
	// archives differ in non-meaningful ways between builds.
	disableAutoGenTag(root)

	header := &doc.GenManHeader{
		Title:   "GO-UDAP",
		Section: "1",
		Source:  "go-udap " + cli.Version,
		Manual:  "go-udap Manual",
		// Pin Date so output is reproducible across builds; the
		// release pipeline can override via SOURCE_DATE_EPOCH or by
		// stamping cli.Version, but for local generation we want
		// `task man` to be idempotent.
		Date: stableDate(),
	}

	if err := doc.GenManTree(root, header, outDir); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote man pages to %s\n", outDir)
}

func disableAutoGenTag(c *cobra.Command) {
	c.DisableAutoGenTag = true
	for _, sub := range c.Commands() {
		disableAutoGenTag(sub)
	}
}

// stableDate returns the SOURCE_DATE_EPOCH if set (used by reproducible
// builds), otherwise the current time. GenManHeader formats this as
// "Month Year" in the man page footer.
func stableDate() *time.Time {
	if s := os.Getenv("SOURCE_DATE_EPOCH"); s != "" {
		var secs int64
		if _, err := fmt.Sscanf(s, "%d", &secs); err == nil {
			t := time.Unix(secs, 0).UTC()
			return &t
		}
	}
	t := time.Now().UTC()
	return &t
}
