package mocksbr

import (
	"context"
	"sync"
	"time"

	"go-udap/udap"
)

// MockTransport implements udap.Transport over an in-process Network.
// Used by hermetic tests to drive a udap.Client without opening a
// socket.
type MockTransport struct {
	net *Network

	mu      sync.Mutex
	pending []pendingReply
	wakeup  chan struct{}
	closed  bool
}

// pendingReply pairs a reply's bytes with the source identifier that
// Recv should surface. For replies generated by Network.Receive the src
// is the device's MAC; for replies queued via InjectReply it's whatever
// the test supplied (typically a fake IP).
type pendingReply struct {
	bytes []byte
	src   string
}

// NewMockTransport returns a MockTransport bound to net.
func NewMockTransport(net *Network) *MockTransport {
	return &MockTransport{
		net:    net,
		wakeup: make(chan struct{}, 1),
	}
}

// Send dispatches a packet to the network. Any replies the network
// produces are queued for retrieval by Recv. Replies whose responding
// device has a non-zero DeviceConfig.Slow are queued via time.AfterFunc
// so the per-device delay shows up on the receiver's wire timeline.
func (t *MockTransport) Send(packet []byte) error {
	for _, reply := range t.net.ReceiveScheduled(packet) {
		t.scheduleReply(reply)
	}
	return nil
}

// scheduleReply queues a reply for retrieval by Recv. Zero-delay replies
// are queued synchronously; non-zero delays go via time.AfterFunc. The
// surface source identifier is extracted from the reply packet itself
// (the device's MAC), matching real-Recv semantics.
func (t *MockTransport) scheduleReply(reply ScheduledReply) {
	src := mockSourceMAC(reply.Bytes)
	if reply.Delay <= 0 {
		t.enqueue(pendingReply{bytes: reply.Bytes, src: src})
		return
	}
	time.AfterFunc(reply.Delay, func() {
		t.enqueue(pendingReply{bytes: reply.Bytes, src: src})
	})
}

// InjectReply queues a fully-formed reply packet for retrieval by Recv,
// surfacing src verbatim instead of extracting it from the packet. Used
// by source-validation tests to simulate a reply arriving from an
// unexpected IP.
func (t *MockTransport) InjectReply(packet []byte, src string) {
	t.enqueue(pendingReply{bytes: packet, src: src})
}

// enqueue appends one reply to the pending queue and wakes any waiter.
// Drops the reply if Close has already been called.
func (t *MockTransport) enqueue(reply pendingReply) {
	t.mu.Lock()
	if t.closed {
		t.mu.Unlock()
		return
	}
	t.pending = append(t.pending, reply)
	t.mu.Unlock()
	t.notifyWaiter()
}

// Recv blocks until a reply packet is available or ctx is cancelled.
// The returned source identifier is whatever was queued with the reply
// — the device's MAC for normal Network-generated replies, or a custom
// value for replies queued via InjectReply.
func (t *MockTransport) Recv(ctx context.Context) ([]byte, string, error) {
	for {
		t.mu.Lock()
		if t.closed {
			t.mu.Unlock()
			return nil, "", context.Canceled
		}
		if len(t.pending) > 0 {
			next := t.pending[0]
			t.pending = t.pending[1:]
			t.mu.Unlock()
			return next.bytes, next.src, nil
		}
		t.mu.Unlock()

		select {
		case <-ctx.Done():
			return nil, "", ctx.Err()
		case <-t.wakeup:
		}
	}
}

// Close marks the transport closed; pending replies are discarded and
// future Recvs return immediately.
func (t *MockTransport) Close() error {
	t.mu.Lock()
	t.closed = true
	t.pending = nil
	t.mu.Unlock()
	t.notifyWaiter()
	return nil
}

func (t *MockTransport) notifyWaiter() {
	select {
	case t.wakeup <- struct{}{}:
	default:
	}
}

// mockSourceMAC extracts the source MAC from a reply packet. Returns
// "" if the packet is too short to contain a valid header.
func mockSourceMAC(reply []byte) string {
	if len(reply) < udap.UDAPHeaderSize {
		return ""
	}
	pkt, _, err := udap.ParsePacket(reply)
	if err != nil {
		return ""
	}
	return formatMAC(pkt.SrcAddress)
}
