name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/release.yaml'
      - '.goreleaser.yaml'
      - '.releaserc.json'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'robinbowes'
    steps:
      - id: create_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.2
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
